version: "3.4"

services:
  sqlServer:
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    ports:
      - 1433:1433
    volumes:
      - D:\Volumes\SqlServer\JornadaMilhas:/var/opt/mssql/data

    environment:
      - MSSQL_SA_PASSWORD=${PASSWORD_SQL}
      - ACCEPT_EULA='Y'

