# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:5045/depoiment
Content-Type: application/json

{
    "Name": "José Silvio",
    "DepoimentDescription": "Descrição Teste",
    "Picture": "VGVzdGUgRm90bw==",
    "UserId": 1
}


