version: "3.4"

services:
  elasticsearch:
   container_name: elasticsearch
   depends_on:
     setup:
       condition: service_healthy
   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   mem_limit: '1GB'
   networks:
    - elastic

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:8.12.0
   ports:
    - 5601:5601
   depends_on:
    elasticsearch:
     condition: service_started
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local